objects/repoevent__c.object
<CustomObject><fields>
        <fullName>original_form__c</fullName>
        <label>original_form</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>repoevents</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>repoevent</label><nameField>
        <displayFormat>g-{00000}</displayFormat>
        <label>repoevent Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>repoevents</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/RESTRepoEventController.cls
@RestResource(urlMapping='/repoevents/*')
global with sharing class RESTRepoEventController {

@HttpPost	
  global static String createNewRepoevent(String payload) {
     System.debug('New Event: '+payload);
   
     if(payload.length() == 0) {
     	System.debug('New Event: empty payload ');
     }
     
     Repoevent__C evt = new Repoevent__C();
     evt.original_form__c = payload;
     
     insert evt;
     System.debug(evt);
     return 'Event persisted: ' + evt.Id;
  }

}